name: Test
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  install:
    name: Test SearXNG install scripts 
    runs-on: ubuntu-22.04
    steps:
    - name: configure network
      run: |
        sudo iptables -F FORWARD
        sudo iptables -P INPUT ACCEPT
        sudo iptables -P FORWARD ACCEPT
        sudo iptables -P OUTPUT ACCEPT
        sudo iptables -t nat -F
        sudo iptables -t mangle -F
        sudo iptables -t raw -F
        sudo iptables -F
        sudo iptables -X
    - name: lxd / lxc init
      run: |
        cat <<EOF | sudo lxd init --preseed
        storage_pools:
        - name: default
          driver: dir
        profiles:
        - name: default
          devices:
            root:
              path: /
              pool: default
              type: disk
        EOF
        sudo lxc network create lxdbr0
        sudo lxc network attach-profile lxdbr0 default eth0
    - name: Info
      run: |
        sudo -H iptables-save
        sudo -H lxc network list
        sudo -H ip a
        sudo -H ip r
        sudo -H lxc profile show default
    - name: Test
      run: |
        sudo lxc launch -q ubuntu:20.04 test
        sudo lxc exec test -- dhclient
        sudo lxc exec test -- ip a
        sudo lxc exec test -- ip r
        echo "Ping gateway"
        sudo lxc exec test -- ping -c1 $(sudo lxc exec test -- ip -j r | jq -r .[0].gateway) 
        echo "Ping 8.8.8.8"
        sudo lxc exec test -- ping -c1 8.8.8.8
    - name: Checkout
      uses: actions/checkout@v3
      with:
        repository: 'return42/searxng'
        ref: 'searxng-install'
    - name: lxc.sh build
      run: sudo -H ./utils/lxc.sh build
    - name: lxc.sh cmd ./utils/searxng.sh install all
      run: sudo -H ./utils/lxc.sh cmd -- FORCE_TIMEOUT=0 ./utils/searxng.sh install all
